## Box 1 imports libraries and defines variables needed

In [1]:
#Box 1

import numpy as np
dircommand=dir
dir="Supernova Data/"
import os
from matplotlib import pyplot as plt
%run "./imf_procedures.py"
imf_index = -2.35
n=1000
m_min = 0.2
m_max = 1000.
m_cut = 100.
index = imf_index
from imf_procedures import make_imf_powerlaw
mass, num_m, mass_limits = make_imf_powerlaw(n,m_min,m_max,m_cut,imf_index)
kobayashi_masses = np.array([13.,15,18,20,25,30,40])


cc_lower_index = np.argwhere(mass >= 12)[0]
cc_upper_index = np.argwhere(mass <= 140)[-1]
cc_lower_index= cc_lower_index[0]
cc_upper_index= cc_upper_index[0]
cc_num = np.sum(num_m[cc_lower_index:cc_upper_index])
Ia_lower_index = np.argwhere(mass >= 1)[0]
Ia_upper_index = np.argwhere(mass <= 8)[-1]
Ia_lower_index= Ia_lower_index[0]
Ia_upper_index= Ia_upper_index[0]
Ia_num = np.sum(num_m[Ia_lower_index:Ia_upper_index])
print(Ia_lower_index)
print(Ia_upper_index)
print(Ia_num)
print(cc_num)

189
432
0.15624595284980305
0.005464584353609598


## Box 2 loads in the data from Heger

In [2]:
# Box 2

import numpy as np
from matplotlib import pyplot as plt

def read_data_heger_2010():
    
    # Load the data from a file
    filename = 'Supernova Data/heger_woosley_CC_2010_apj300379t8_mrt.txt'

    data = np.loadtxt(filename,skiprows=17,usecols=[0,1,3,5])
    data_cut = np.loadtxt(filename,skiprows=17,usecols=[2],dtype=str)
    data_isotope = np.loadtxt(filename,skiprows=17,usecols=[4],dtype=str)

    #print(data.size)
    #print(data.shape)
    #print(data_cut.shape)

    # mass, energy, mixing, yield

    heger_solar_mass = data[:,0]
    heger_energy = data[:,1]
    heger_mixing = data[:,2]
    heger_yield = data[:,3]

    heger_cut = data_cut
    heger_isotope = data_isotope

    heger_solar_masses = np.unique(heger_solar_mass)
    heger_energies = np.unique(heger_energy)
    heger_mixings = np.unique(heger_mixing)
    heger_cuts = np.unique(heger_cut)
    
    heger_isotopes_unique, isotopes_indicies = np.unique(heger_isotope,return_index=True)
    heger_isotopes = heger_isotope[np.sort(isotopes_indicies)]

    #print(heger_masses.size, heger_energies.size, heger_mixings.size, heger_cuts.size)

    #print(heger_isotopes)

    # So we have up to 283 isotopes per model, , but don't have every isotope for every model.
    # And 120 masses for each set of models with the S4 cut.
    # There are then 10 different energies and 4 different mixings, for 40 different sets of models.
    # In Morsony et al. 2015, we used all 10 different energies, but only the 0 mixing set.
    
    
    # So let's make a big array to hold all the sets of models:
    
    heger_2010_all_yields = np.zeros([heger_isotopes.size, heger_solar_masses.size, heger_energies.size, heger_mixings.size])
    
    #print(heger_2010_all_yields.shape)
    #print(heger_2010_all_yields.size)
    
    for i in np.arange(heger_yield.size):
    #for i in np.arange(10):
        if heger_cut[i]=='S4':
            i0 = np.argwhere(heger_isotopes == heger_isotope[i])
            i1 = np.argwhere(heger_solar_masses == heger_solar_mass[i])
            i2 = np.argwhere(heger_energies == heger_energy[i])
            i3 = np.argwhere(heger_mixings == heger_mixing[i])
            
            heger_2010_all_yields[i0,i1,i2,i3] = heger_yield[i]
    
    #print(heger_2010_all_yields.shape)

    # This only returns the data for the S4 cut.
    
    return heger_2010_all_yields,heger_isotopes,heger_solar_masses,heger_energies,heger_mixings

heger_2010_isotope_masses, heger_2010_isotope_names, heger_2010_solar_masses, heger_2010_energy, heger_2010_mixing = read_data_heger_2010()

print('This is all using only the S4 cutoff:')
print('Heger & Woosley 2010 Energies = ',heger_2010_energy)
print('Heger & Woosley 2010 Mixing = ',heger_2010_mixing)
print('Heger & Woosley 2010 Solar Masses = ')
print(heger_2010_solar_masses)
print('Heger & Woosley 2010 Isotopes Names = ')
print(heger_2010_isotope_names)

print('Heger & Woosley 2010 all yields shape = ',heger_2010_isotope_masses.shape)



# This is an example of picking out one particule set of models:
# This one is at energy of 0.9e51 erg and mixing of 0:

heger_2010_e9_m0 = heger_2010_isotope_masses[:,:,2,0]

print(' ')
print('Shape of model set with energy  = 0.9, mixing = 0:',heger_2010_e9_m0.shape)

This is all using only the S4 cutoff:
Heger & Woosley 2010 Energies =  [ 0.3  0.6  0.9  1.2  1.5  1.8  2.4  3.   5.  10. ]
Heger & Woosley 2010 Mixing =  [0.      0.001   0.00158 0.00251]
Heger & Woosley 2010 Solar Masses = 
[ 10.   10.2  10.4  10.5  10.6  10.7  10.8  10.9  11.   11.1  11.2  11.3
  11.4  11.5  11.6  11.7  11.8  11.9  12.   12.2  12.4  12.6  12.8  13.
  13.2  13.4  13.6  13.8  14.   14.2  14.4  14.6  14.8  15.   15.2  15.4
  15.6  15.8  16.   16.2  16.4  16.6  16.8  17.   17.1  17.2  17.3  17.4
  17.5  17.6  17.7  17.8  17.9  18.   18.1  18.2  18.3  18.4  18.5  18.6
  18.7  18.8  18.9  19.   19.2  19.4  19.6  19.8  20.   20.5  21.   21.5
  22.   22.5  23.   23.5  24.   24.5  25.   25.5  26.   26.5  27.   27.5
  28.   28.5  29.   29.5  30.   30.5  31.   31.5  32.   32.5  33.   33.5
  34.   34.5  35.   36.   37.   38.   39.   40.   41.   42.   43.   44.
  45.   50.   55.   60.   65.   70.   75.   80.   85.   90.   95.  100. ]
Heger & Woosley 2010 Isotopes Names = 
['H1' '

## Box 3 reads in the supernova data and defines the masses of all of the isotopes

In [3]:
# Box 3

#reading in all the files mass

#Shen
data =np.genfromtxt(dir+"Shen IA 2018",skip_header=234, dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
shen_mass = data
shen_mass = np.transpose(shen_mass)
shen_mass_float = shen_mass[1:,:].astype(np.float)
shen_mass1 = shen_mass[0:1,:]
#print(np.shape(data))
#print(shen_mass)
#print(np.shape(shen_mass))
#print(shen_mass1)
#print(data)
#print(shen_mass[1:,0])
#print(shen_mass_float[:,0])

#Kobayashi
data = np.loadtxt(dir+"kobayashi_2006_core_collapse.txt",skiprows=26,usecols=(2,3,4,5,6,7,8) ) #, delimiter=" ", skiprows=6, usecols=1)
kobayashi_mass= data
#print(data)

#Heger_Woosley
data = np.loadtxt(dir+"heger_woosley_2002_.txt",skiprows=24,usecols=(1,2,3,4,5,6,7,8,9,10,11,12,13,14) ) #
#print(data)
heger_woosley_mass= data
#column number/ solar mass
#1-65
#2-70
#3-75
#4-80
#5-85
#6-90
#7-95
#8-100
#9-105
#10-110
#11-115
#12-120
#13-125
#14-130
heger_woosley_stellar_masses = np.array([65,70,75,80,90,95,100,105,110,115,120,125,130])
#print(heger_woosley_stellar_masses)

#Heger Woosley 2010




#Iwamoto
data = np.loadtxt(dir+"Iwamoto data",skiprows=2,usecols=(2,5)) #, delimiter=" ", skiprows=6, usecols=1)

#print(np.shape(data))

#print(data)

Iwamoto_mass = data

#Seitenzahl
data = np.loadtxt(dir+"Seitenzahl.test2.txt",skiprows=1,usecols=(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17)) #, delimiter=" ", skiprows=6, usecols=1)

Seitenzahl_mass = data

#Sukhbold
data = np.loadtxt(dir+"sukhbold n20 w18 data table 2.txt",skiprows=4) #, delimiter=" ", skiprows=6, usecols=1)
sukhbold_mass = data

#N20
import os
files = os.listdir(dir+"nucleosynthesis_yields/N20")
#print(len(files))
data = np.loadtxt(dir+"nucleosynthesis_yields/N20/"+files[0],skiprows=1,usecols=(1,2)) #, delimiter=" ", skiprows=6, usecols=1)
#print(np.shape(data))
data_shape = np.shape(data)
#print(data_shape[0])
N20_big_data = np.zeros([len(files),data_shape[0],data_shape[1]])
files = os.listdir(dir+"nucleosynthesis_yields/N20")
#print(len(files))
#print(files)
data = np.loadtxt(dir+"nucleosynthesis_yields/N20/"+files[0],skiprows=1,usecols=(1,2)) #, delimiter=" ", skiprows=6, usecols=1)
#print(np.shape(data))
data_shape = np.shape(data)
#print(data_shape[0])
N20_big_data = np.zeros([len(files),data_shape[0],data_shape[1]])
#print(files[53][1:-12])
N20_masses = np.zeros([len(files)])
for i in np.arange(len(files)):
    data = np.loadtxt(dir+"nucleosynthesis_yields/N20/"+files[i],skiprows=1,usecols=(1,2))
    #print(files[i])
    if files[i] != 's14.0.yield_table':
        N20_big_data[i,:,:] = data[:,:]
        N20_masses[i] = float(files[i][1:-12])


#W18
import os
files = os.listdir(dir+"nucleosynthesis_yields/W18")
#print(len(files))
#print(files[53][1:-12])
W18_masses = np.zeros([len(files)])
#print(files)
data = np.loadtxt(dir+"nucleosynthesis_yields/W18/"+files[0],skiprows=1,usecols=(1,2)) #, delimiter=" ", skiprows=6, usecols=1)
#print(np.shape(data))
data_shape = np.shape(data)
#print(data_shape[0])
W18_big_data = np.zeros([len(files),data_shape[0],data_shape[1]])
for i in np.arange(len(files)):
    data = np.loadtxt(dir+"nucleosynthesis_yields/W18/"+files[i],skiprows=1,usecols=(1,2))
    #print(files[i])
    if files[i] != 's14.0.yield_table':
        W18_big_data[i,:,:] = data[:,:]
        W18_masses[i] = float(files[i][1:-12])

#WDD2
data = np.loadtxt(dir+"wdd2_solar.txt",skiprows=2,usecols=(0,1,2,3))
#print(data)
wdd2_mass = data

#W7
data = np.loadtxt(dir+"w7_solar.txt",skiprows=2) #, delimiter=" ", skiprows=6, usecols=1)
#print(data)
w7_mass = data

#karakas_a2_0200

num_isotopes=77
num_stellar_masses=16

karakas_a2_mass0200 = np.zeros((num_isotopes,num_stellar_masses))
#karakas_a2_difference = data
karakas_a2_stellar_masses=np.array([1.00,1.25,1.50,1.75,1.90,2.00,2.25,2.50,3.00,3.50,4.00,4.50,5.00,5.50,6.00,6.50,])

data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=2,skip_footer= 1170, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
#karakas_a2_1_msun_yield = data
karakas_a2_mass0200[:,0]=np.copy(data)
#print(data)
#print(karakas_a2_difference.shape)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=81,skip_footer= 1092, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,1]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=160,skip_footer= 1014, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,2]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=239,skip_footer= 936, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,3]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=318,skip_footer= 858, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,4]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=397,skip_footer= 780, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,5]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=476,skip_footer= 702, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,6]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=555,skip_footer= 624, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,7]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=634,skip_footer= 546, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,8]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=713,skip_footer= 468, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,9]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=792,skip_footer= 390, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,10]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=871,skip_footer= 312, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,11]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=950,skip_footer= 234, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,12]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=1029,skip_footer= 156, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,13]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=1108,skip_footer= 78, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,14]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a2.txt", skip_header=1187,skip_footer= 0, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a2_mass0200[:,15]=np.copy(data)
#print(data1)
#print(karakas_a2_mass0200[0,:])

#karakas_a3_0800

num_isotopes=77
num_stellar_masses=15
karakas_a3_mass0080 = np.zeros((num_isotopes,num_stellar_masses))
#karakas_a3_mass0080 = data
karakas_a3_stellar_masses=np.array([1.00,1.25,1.50,1.75,1.90,2.10,2.25,2.50,3.00,3.50,4.00,4.50,5.00,5.50,6.00])
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=2,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
#karakas_a3_1_msun_yield = data
karakas_a3_mass0080[:,0]=np.copy(data)
#print(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=81,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,1]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=160,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,2]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=239,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,3]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=318,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,4]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=397,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,5]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=476,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,6]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=555,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,7]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=634,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,8]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=713,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,9]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=792,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,10]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=871,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,11]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=950,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,12]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=1029,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,13]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a3.txt", skip_header=1108,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a3_mass0080[:,14]=np.copy(data)
#print(data1)
#print(karakas_a3_mass0080[0,:])

#karakas_a4_0040

num_isotopes=77
num_stellar_masses=15

karakas_a4_mass0040 = np.zeros((num_isotopes,num_stellar_masses))
#karakas_a4_mass0040 = data
karakas_a4_stellar_masses=np.array([1.00,1.25,1.50,1.75,1.90,2.10,2.25,2.50,3.00,3.50,4.00,4.50,5.00,5.50,6.00])

data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=2,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
#karakas_a4_1_msun_yield = data
karakas_a4_mass0040[:,0]=np.copy(data)
#print(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=81,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,1]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=160,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,2]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=239,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,3]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=318,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,4]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=397,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,5]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=476,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,6]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=555,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,7]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=634,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,8]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=713,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,9]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=792,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,10]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=871,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,11]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=950,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,12]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=1029,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,13]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a4.txt", skip_header=1108,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a4_mass0040[:,14]=np.copy(data)
#print(data1)
#print(karakas_a4_mass0040[0,:])

#karakas_a5_0001

num_isotopes=77
num_stellar_masses=15

karakas_a5_mass0001 = np.zeros((num_isotopes,num_stellar_masses))
#karakas_a5_mass0001 = data
karakas_a5_stellar_masses=np.array([1.00,1.25,1.50,1.75,1.90,2.00,2.25,2.50,3.00,3.50,4.00,4.50,5.00,5.50,6.00])

data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=2,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
#karakas_a5_1_msun_yield = data
karakas_a5_mass0001[:,0]=np.copy(data)
#print(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=81,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,1]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=160,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,2]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=239,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,3]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=318,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,4]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=397,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,5]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=476,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,6]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=555,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,7]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=634,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,8]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=713,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,9]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=792,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,10]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=871,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,11]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=950,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,12]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=1029,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,13]=np.copy(data)
data = np.genfromtxt(dir+"karakas/table_a5.txt", skip_header=1108,max_rows=77, usecols=[3] ,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
karakas_a5_mass0001[:,14]=np.copy(data)


#Nomoto 02 2006
data = np.loadtxt(dir+"nomoto_0020_test.txt",skiprows=4,usecols=[1,2,3,4,5,6,7], dtype='str' ) #, delimiter=" ", skiprows=6, usecols=1)
nomoto_mass= data.astype(float)

nomoto_stellar_masses=np.array([13,15,18,20,25,30,40])

#Heger Woosley 2010
print(heger_2010_isotope_masses)

print('test')
print(W18_big_data)

[[[[5.29092e+00 5.29092e+00 5.29092e+00 5.29092e+00]
   [5.29093e+00 5.29093e+00 5.29093e+00 5.29093e+00]
   [5.29093e+00 5.29093e+00 5.29093e+00 5.29093e+00]
   ...
   [5.29094e+00 5.29094e+00 5.29094e+00 5.29094e+00]
   [5.29096e+00 5.29096e+00 5.29096e+00 5.29096e+00]
   [5.29099e+00 5.29099e+00 5.29099e+00 5.29099e+00]]

  [[5.38541e+00 5.38541e+00 5.38541e+00 5.38541e+00]
   [5.38541e+00 5.38541e+00 5.38541e+00 5.38541e+00]
   [5.38541e+00 5.38541e+00 5.38541e+00 5.38541e+00]
   ...
   [5.38541e+00 5.38541e+00 5.38541e+00 5.38541e+00]
   [5.38542e+00 5.38542e+00 5.38542e+00 5.38542e+00]
   [5.38542e+00 5.38542e+00 5.38542e+00 5.38542e+00]]

  [[5.40169e+00 5.40169e+00 5.40169e+00 5.40169e+00]
   [5.40169e+00 5.40169e+00 5.40169e+00 5.40169e+00]
   [5.40169e+00 5.40169e+00 5.40169e+00 5.40169e+00]
   ...
   [5.40170e+00 5.40170e+00 5.40170e+00 5.40171e+00]
   [5.40172e+00 5.40172e+00 5.40172e+00 5.40172e+00]
   [5.40176e+00 5.40176e+00 5.40176e+00 5.40176e+00]]

  ...

  [[2.45996e

## Boxes 4 and 5 create the isotope map for each model

In [4]:
#reading in all the files isotopes

#Shen

data = np.genfromtxt(dir+"Shen IA 2018", skip_header=13,skip_footer= 202, usecols=4,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
shen_isotopes = data
#print(shen_isotopes)
#print(shen_isotopes.shape)
data = np.genfromtxt(dir+"Shen IA 2018", skip_header=101,skip_footer= 86, usecols=3,dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
#print(data)
shen_isotopes = np.concatenate([shen_isotopes,data])
#print(shen_isotopes)
#print(shen_isotopes.shape)

#Kobayashi

kobayashi_isotopes_000 = np.copy(kobayashi_mass[0:83,:])
kobayashi_isotopes_001 = np.copy(kobayashi_mass[85:168,:])
kobayashi_isotopes_004 = np.copy(kobayashi_mass[170:253,:])
kobayashi_isotopes_02 = np.copy(kobayashi_mass[255:338,:])


#Heger-Woosley
heger_woosley_isotopes = data = np.loadtxt(dir+"heger_woosley_2002_.txt",skiprows=24,usecols=(1,2,3,4,5,6,7,8,9,10,11,12,13,14)) #, delimiter=" ", skiprows=6, usecols=1)
#for i in np.arange(len(data)):
#       print(i,data[i,0],data[i,1])

#Iwamoto
data = np.loadtxt(dir+"Iwamoto data",skiprows=2,usecols=(2,5)) #, delimiter=" ", skiprows=6, usecols=1)
#for i in np.arange(len(data)):
#    print(i,data[i,0],data[i,1])
    
Iwamoto_w7_isotopes = data

#Seintzahl

data = np.loadtxt(dir+"Seitenzahl.test2.txt",skiprows=1,usecols=(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17)) #, delimiter=" ", skiprows=6, usecols=1)
Seitenzahl_mass = data
#print(np.shape(data))
#print(data)
isotopes_Seitenzahl_test2 = np.loadtxt(dir+"Seitenzahl.test2.txt",dtype='str',skiprows=1,usecols=(0)) #, delimiter=" ", skiprows=6, usecols=1)
#print(isotopes_Seitenzahl_test2)



#Sukhbold
data = np.loadtxt(dir+"sukhbold n20 w18 data table 2.txt",skiprows=4) #, delimiter=" ", skiprows=6, usecols=1)
for i in np.arange(len(data)):
    #print(i,data[i,0],data[i,1])
    
    sukhbold_isotopes = data

#N20

#none

#W18

#none

#WDD2

data = np.loadtxt(dir+"wdd2_solar.txt",skiprows=2) #, delimiter=" ", skiprows=6, usecols=1)
for i in np.arange(len(data)):
    #print(i,data[i,0],data[i,1])
    wdd2_solar_isotopes = data

#W7
data = np.loadtxt(dir+"w7_solar.txt",skiprows=2) #, delimiter=" ", skiprows=6, usecols=1)
for i in np.arange(len(data)):
    #print(i,data[i,0],data[i,1])
    w7_solar_isotopes = data

#karakas_a2_0200
karakas_a2_0200_isotopes = karakas_a2_mass0200[:,0]

#karakas_a3_0080
karakas_a3_0080_isotopes = karakas_a3_mass0080[:,0]

#karakas_a4_0040
karakas_a4_0040_isotopes = karakas_a4_mass0040[:,0]

#karakas_a5_0001
karakas_a5_0001_isotopes = karakas_a5_mass0001[:,0]

#nomoto
nomoto_isotopes= nomoto_mass

#Heger Woosley 2010

heger_2010_isotopes = heger_2010_isotope_masses
print('done')

done


In [5]:
#reading all the files isotope map

#shen
data = np.loadtxt(dir+"nucleosynthesis_yields/W18/"+files[0],skiprows=1,usecols=(0),dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
W18_isotope_names = data 

all_isotope_names = W18_isotope_names


    
shen_isotope_map = np.zeros(len(shen_mass[:,0]),dtype='int')

#shen_isotope_map[0] = 8 #np.arange(8)

shen_isotope_map[:] = -1
#shen_isotope_map[5:207] = np.arange(202)+0
shen_isotope_map[5:11] = np.arange(6)+0
shen_isotope_map[12] = np.arange(1)+6
shen_isotope_map[15:19]= np.arange(4)+7
shen_isotope_map[20:22]= np.arange(2)+11
shen_isotope_map[24:27]= np.arange(3)+13
shen_isotope_map[30] = np.arange(1)+16
shen_isotope_map[33:36]= np.arange(3)+17
shen_isotope_map[39] = np.arange(1)+20
shen_isotope_map[42:45] = np.arange(3)+21
shen_isotope_map[48] = np.arange(1)+24
shen_isotope_map[51:54] = np.arange(3)+25
shen_isotope_map[58] = np.arange(1)+28
shen_isotope_map[63:66] = np.arange(3)+29
shen_isotope_map[67] = np.arange(1)+32
shen_isotope_map[69] = np.arange(1)+33
shen_isotope_map[71] = np.arange(1)+34
shen_isotope_map[74] = np.arange(1)+35
shen_isotope_map[76] = np.arange(1)+36
shen_isotope_map[78] = np.arange(1)+37
shen_isotope_map[80:83] = np.arange(3)+38
shen_isotope_map[87] = np.arange(1)+41
shen_isotope_map[89:92] = np.arange(3)+42
shen_isotope_map[93] = np.arange(1)+45
shen_isotope_map[95] = np.arange(1)+46
shen_isotope_map[99] = np.arange(1)+47
shen_isotope_map[109:114] = np.arange(5)+48
shen_isotope_map[121:123] = np.arange(2)+53
shen_isotope_map[131] = np.arange(1)+55
shen_isotope_map[133:136] = np.arange(3)+56
shen_isotope_map[144] = np.arange(1)+59
shen_isotope_map[149] = np.arange(1)+60
shen_isotope_map[151:154] = np.arange(3)+61
shen_isotope_map[163] = np.arange(1)+64
shen_isotope_map[171] = np.arange(1)+65
shen_isotope_map[173:176] = np.arange(3)+66
shen_isotope_map[181] = np.arange(1)+69
shen_isotope_map[183] = np.arange(1)+70
shen_isotope_map[190] = np.arange(1)+71
shen_isotope_map[192:194] = np.arange(2)+72


shen_isotope_map_float = shen_isotope_map[1:]

#kobayashi
kobayashi_isotopes = data = kobayashi_isotopes_000
kobayashi_isotope_map = np.zeros(len(kobayashi_isotopes[:,0]),dtype='int')

kobayashi_isotope_map[0] = 8 #np.arange(8)

kobayashi_isotope_map[0:83] = np.arange(83)+0
kobayashi_isotope_map = kobayashi_isotope_map[0:83]

#Heger-Woosley
heger_woosley_isotope_map = np.zeros(len(heger_woosley_isotopes[:,0]),dtype='int')

heger_woosley_isotope_map[0] = 8 #np.arange(8)

heger_woosley_isotope_map[0:81] = np.arange(81)+0

#Iwamoto
Iwamoto_isotope_map = np.zeros(len(Iwamoto_w7_isotopes[:,0]),dtype='int')

Iwamoto_isotope_map[0] = 8 #np.arange(8)

Iwamoto_isotope_map[0:66] = np.arange(66)+9
Iwamoto_isotope_map[30:66] = np.arange(36)+9+30+1

#Seitenzahl
Seitenzahl_isotope_map = np.zeros(len(isotopes_Seitenzahl_test2),dtype='int')
Seitenzahl_isotope_map[0] = 8 #np.arange(8)
Seitenzahl_isotope_map[0:30] = np.arange(30)+9
Seitenzahl_isotope_map[30:62] = np.arange(32)+40
Seitenzahl_isotope_map[62:68] = np.arange(6)+73

#Sukhbold
sukhbold_isotope_map = np.zeros(len(sukhbold_isotopes[:,0]),dtype='int')
sukhbold_isotope_map[0] = 8 #np.arange(8)
sukhbold_isotope_map[0:105] = np.arange(105)+0

#N20
N20_isotope_map= np.arange(303)

#W18
W18_isotope_map= np.arange(303)

#WDD2
wdd2_isotope_map = np.zeros(len(wdd2_solar_isotopes[:,0]),dtype='int')

wdd2_isotope_map[0] = 8 #np.arange(8)

wdd2_isotope_map[0:77] = np.arange(77)+0

#W7
w7_isotope_map = np.zeros(len(w7_solar_isotopes[:,0]),dtype='int')
w7_isotope_map[0] = 8 #np.arange(8)
w7_isotope_map[0:77] = np.arange(77)+0

#karakas_a2_0200
karakas_a2_0200_isotope_map = np.zeros(len(karakas_a2_0200_isotopes[:]),dtype='int')

karakas_a2_0200_isotope_map[0] = 8 #np.arange(8)

karakas_a2_0200_isotope_map[0:2] = -1
karakas_a2_0200_isotope_map[2:6] = np.arange(4)
karakas_a2_0200_isotope_map[6] = 5
karakas_a2_0200_isotope_map[7:9] = -1
karakas_a2_0200_isotope_map[9:11] = np.arange(2)+9
karakas_a2_0200_isotope_map[11:13] = -1
karakas_a2_0200_isotope_map[13:15] = np.arange(2)+11
karakas_a2_0200_isotope_map[15:17] = -1
karakas_a2_0200_isotope_map[17:20] = np.arange(3)+13
karakas_a2_0200_isotope_map[20:23] = -1
karakas_a2_0200_isotope_map[23] = np.arange(1)+16
karakas_a2_0200_isotope_map[24:26] = -1
karakas_a2_0200_isotope_map[26:29] = np.arange(3)+17
karakas_a2_0200_isotope_map[29:32] = -1
karakas_a2_0200_isotope_map[32] = np.arange(1)+20
karakas_a2_0200_isotope_map[33:35] = -1
karakas_a2_0200_isotope_map[35:38] = np.arange(3)+21
karakas_a2_0200_isotope_map[38:42] = -1
karakas_a2_0200_isotope_map[42] = np.arange(1)+24
karakas_a2_0200_isotope_map[43:46] = -1
karakas_a2_0200_isotope_map[46:49] = np.arange(3)+25
karakas_a2_0200_isotope_map[49:54] = -1
karakas_a2_0200_isotope_map[54] = np.arange(1)+28
karakas_a2_0200_isotope_map[55:58] = -1
karakas_a2_0200_isotope_map[58:61] = np.arange(3)+29
karakas_a2_0200_isotope_map[61] = -1
karakas_a2_0200_isotope_map[62] = np.arange(1)+60
karakas_a2_0200_isotope_map[63] = np.arange(1)+ 296
karakas_a2_0200_isotope_map[64:67] = np.arange(3)+ 61
karakas_a2_0200_isotope_map[67] = -1
karakas_a2_0200_isotope_map[68] = np.arange(1)+ 297
karakas_a2_0200_isotope_map[67] = -1
karakas_a2_0200_isotope_map[70] = np.arange(1)+ 64
karakas_a2_0200_isotope_map[71:73] = -1
karakas_a2_0200_isotope_map[73] = np.arange(1) + 65
karakas_a2_0200_isotope_map[74] = -1
karakas_a2_0200_isotope_map[75:77] = np.arange(2) + 66

#karakas_a3_0080
karakas_a3_0080_isotope_map = np.zeros(len(karakas_a3_0080_isotopes[:]),dtype='int')

karakas_a3_0080_isotope_map[0] = 8 #np.arange(8)

karakas_a3_0080_isotope_map[0:2] = -1
karakas_a3_0080_isotope_map[2:6] = np.arange(4)
karakas_a3_0080_isotope_map[6] = 5
karakas_a3_0080_isotope_map[7:9] = -1
karakas_a3_0080_isotope_map[9:11] = np.arange(2)+9
karakas_a3_0080_isotope_map[11:13] = -1
karakas_a3_0080_isotope_map[13:15] = np.arange(2)+11
karakas_a3_0080_isotope_map[15:17] = -1
karakas_a3_0080_isotope_map[17:20] = np.arange(3)+13
karakas_a3_0080_isotope_map[20:23] = -1
karakas_a3_0080_isotope_map[23] = np.arange(1)+16
karakas_a3_0080_isotope_map[24:26] = -1
karakas_a3_0080_isotope_map[26:29] = np.arange(3)+17
karakas_a3_0080_isotope_map[29:32] = -1
karakas_a3_0080_isotope_map[32] = np.arange(1)+20
karakas_a3_0080_isotope_map[33:35] = -1
karakas_a3_0080_isotope_map[35:38] = np.arange(3)+21
karakas_a3_0080_isotope_map[38:42] = -1
karakas_a3_0080_isotope_map[42] = np.arange(1)+24
karakas_a3_0080_isotope_map[43:46] = -1
karakas_a3_0080_isotope_map[46:49] = np.arange(3)+25
karakas_a3_0080_isotope_map[49:54] = -1
karakas_a3_0080_isotope_map[54] = np.arange(1)+28
karakas_a3_0080_isotope_map[55:58] = -1
karakas_a3_0080_isotope_map[58:61] = np.arange(3)+29
karakas_a3_0080_isotope_map[61] = -1
karakas_a3_0080_isotope_map[62] = np.arange(1)+60
karakas_a3_0080_isotope_map[63] = np.arange(1)+ 296
karakas_a3_0080_isotope_map[64:67] = np.arange(3)+ 61
karakas_a3_0080_isotope_map[67] = -1
karakas_a3_0080_isotope_map[68] = np.arange(1)+ 297
karakas_a3_0080_isotope_map[67] = -1
karakas_a3_0080_isotope_map[70] = np.arange(1)+ 64
karakas_a3_0080_isotope_map[71:73] = -1
karakas_a3_0080_isotope_map[73] = np.arange(1) + 65
karakas_a3_0080_isotope_map[74] = -1
karakas_a3_0080_isotope_map[75:77] = np.arange(2) + 66

#karakas_a4_0040
karakas_a4_0040_isotope_map = np.zeros(len(karakas_a4_0040_isotopes[:]),dtype='int')

karakas_a4_0040_isotope_map[0] = 8 #np.arange(8)

karakas_a4_0040_isotope_map[0:2] = -1
karakas_a4_0040_isotope_map[2:6] = np.arange(4)
karakas_a4_0040_isotope_map[6] = 5
karakas_a4_0040_isotope_map[7:9] = -1
karakas_a4_0040_isotope_map[9:11] = np.arange(2)+9
karakas_a4_0040_isotope_map[11:13] = -1
karakas_a4_0040_isotope_map[13:15] = np.arange(2)+11
karakas_a4_0040_isotope_map[15:17] = -1
karakas_a4_0040_isotope_map[17:20] = np.arange(3)+13
karakas_a4_0040_isotope_map[20:23] = -1
karakas_a4_0040_isotope_map[23] = np.arange(1)+16
karakas_a4_0040_isotope_map[24:26] = -1
karakas_a4_0040_isotope_map[26:29] = np.arange(3)+17
karakas_a4_0040_isotope_map[29:32] = -1
karakas_a4_0040_isotope_map[32] = np.arange(1)+20
karakas_a4_0040_isotope_map[33:35] = -1
karakas_a4_0040_isotope_map[35:38] = np.arange(3)+21
karakas_a4_0040_isotope_map[38:42] = -1
karakas_a4_0040_isotope_map[42] = np.arange(1)+24
karakas_a4_0040_isotope_map[43:46] = -1
karakas_a4_0040_isotope_map[46:49] = np.arange(3)+25
karakas_a4_0040_isotope_map[49:54] = -1
karakas_a4_0040_isotope_map[54] = np.arange(1)+28
karakas_a4_0040_isotope_map[55:58] = -1
karakas_a4_0040_isotope_map[58:61] = np.arange(3)+29
karakas_a4_0040_isotope_map[61] = -1
karakas_a4_0040_isotope_map[62] = np.arange(1)+60
karakas_a4_0040_isotope_map[63] = np.arange(1)+ 296
karakas_a4_0040_isotope_map[64:67] = np.arange(3)+ 61
karakas_a4_0040_isotope_map[67] = -1
karakas_a4_0040_isotope_map[68] = np.arange(1)+ 297
karakas_a4_0040_isotope_map[67] = -1
karakas_a4_0040_isotope_map[70] = np.arange(1)+ 64
karakas_a4_0040_isotope_map[71:73] = -1
karakas_a4_0040_isotope_map[73] = np.arange(1) + 65
karakas_a4_0040_isotope_map[74] = -1
karakas_a4_0040_isotope_map[75:77] = np.arange(2) + 66

#karakas_a5_0001
karakas_a5_0001_isotope_map = np.zeros(len(karakas_a5_0001_isotopes[:]),dtype='int')

karakas_a5_0001_isotope_map[0] = 8 #np.arange(8)

karakas_a5_0001_isotope_map[0:2] = -1
karakas_a5_0001_isotope_map[2:6] = np.arange(4)
karakas_a5_0001_isotope_map[6] = 5
karakas_a5_0001_isotope_map[7:9] = -1
karakas_a5_0001_isotope_map[9:11] = np.arange(2)+9
karakas_a5_0001_isotope_map[11:13] = -1
karakas_a5_0001_isotope_map[13:15] = np.arange(2)+11
karakas_a5_0001_isotope_map[15:17] = -1
karakas_a5_0001_isotope_map[17:20] = np.arange(3)+13
karakas_a5_0001_isotope_map[20:23] = -1
karakas_a5_0001_isotope_map[23] = np.arange(1)+16
karakas_a5_0001_isotope_map[24:26] = -1
karakas_a5_0001_isotope_map[26:29] = np.arange(3)+17
karakas_a5_0001_isotope_map[29:32] = -1
karakas_a5_0001_isotope_map[32] = np.arange(1)+20
karakas_a5_0001_isotope_map[33:35] = -1
karakas_a5_0001_isotope_map[35:38] = np.arange(3)+21
karakas_a5_0001_isotope_map[38:42] = -1
karakas_a5_0001_isotope_map[42] = np.arange(1)+24
karakas_a5_0001_isotope_map[43:46] = -1
karakas_a5_0001_isotope_map[46:49] = np.arange(3)+25
karakas_a5_0001_isotope_map[49:54] = -1
karakas_a5_0001_isotope_map[54] = np.arange(1)+28
karakas_a5_0001_isotope_map[55:58] = -1
karakas_a5_0001_isotope_map[58:61] = np.arange(3)+29
karakas_a5_0001_isotope_map[61] = -1
karakas_a5_0001_isotope_map[62] = np.arange(1)+60
karakas_a5_0001_isotope_map[63] = np.arange(1)+ 296
karakas_a5_0001_isotope_map[64:67] = np.arange(3)+ 61
karakas_a5_0001_isotope_map[67] = -1
karakas_a5_0001_isotope_map[68] = np.arange(1)+ 297
karakas_a5_0001_isotope_map[67] = -1
karakas_a5_0001_isotope_map[70] = np.arange(1)+ 64
karakas_a5_0001_isotope_map[71:73] = -1
karakas_a5_0001_isotope_map[73] = np.arange(1) + 65
karakas_a5_0001_isotope_map[74] = -1
karakas_a5_0001_isotope_map[75:77] = np.arange(2) + 66


#Nomoto
nomoto_isotope_map = np.zeros(len(nomoto_isotopes[:,0]),dtype='int')
nomoto_isotope_map[0] = 8 #np.arange(8)
nomoto_isotope_map[0:80] = np.arange(80)+0

#Heger 2010
heger_2010_isotope_map = np.zeros(len(heger_2010_isotope_names[:]),dtype='int')
heger_2010_isotope_map[0] = 8 #np.arange(8)
heger_2010_isotope_map[0:83] = np.arange(83)
heger_2010_isotope_map[83:89]= 84+ np.arange(6)
heger_2010_isotope_map[89:96]= 91+ np.arange(7)
heger_2010_isotope_map[96]= 99
heger_2010_isotope_map[97:105]= 101+ np.arange(8)
heger_2010_isotope_map[105:110]= 111+ np.arange(5)
heger_2010_isotope_map[110:111]= 116+ np.arange(1)
heger_2010_isotope_map[111:112]= 119+ np.arange(1)
heger_2010_isotope_map[112]= 83
heger_2010_isotope_map[113]=90
heger_2010_isotope_map[114]= 98
heger_2010_isotope_map[115]= 100
heger_2010_isotope_map[116:118]= 109+ np.arange(2)
heger_2010_isotope_map[118:120]= 117+np.arange(2)
heger_2010_isotope_map[120:135]= 120+np.arange(15)
heger_2010_isotope_map[135:144]= 136+np.arange(9)
heger_2010_isotope_map[144:155]= 146+np.arange(11)
heger_2010_isotope_map[155:163]= 158+np.arange(8)
heger_2010_isotope_map[163:171]= 168+np.arange(8)
heger_2010_isotope_map[171:178]= 178+np.arange(7)
heger_2010_isotope_map[178:181]= 187+np.arange(3)
heger_2010_isotope_map[181]= 191
heger_2010_isotope_map[182]= 145
heger_2010_isotope_map[183]= 167
heger_2010_isotope_map[184:186]= 176+np.arange(2)
heger_2010_isotope_map[186:188]= 185+np.arange(2)
heger_2010_isotope_map[188]= 190
heger_2010_isotope_map[189:194]= 192+np.arange(5)
heger_2010_isotope_map[194:210]= 198+np.arange(16)
heger_2010_isotope_map[210:217]= 215+np.arange(7)
heger_2010_isotope_map[217:231]= 223+np.arange(14)
heger_2010_isotope_map[231:238]= 239+np.arange(7)
heger_2010_isotope_map[238:243]= 247+np.arange(5)
heger_2010_isotope_map[243]= 252
heger_2010_isotope_map[244:252]= 254+np.arange(8)
heger_2010_isotope_map[252:272]= 263+np.arange(20)
heger_2010_isotope_map[272]= 135
heger_2010_isotope_map[273]= 157
heger_2010_isotope_map[274]= 166
heger_2010_isotope_map[275]= 214
heger_2010_isotope_map[276]= 229
heger_2010_isotope_map[277]= 246

heger_2010_isotope_map[278]= 262
heger_2010_isotope_map[279]= 197
heger_2010_isotope_map[280]= 222
heger_2010_isotope_map[281]= 238
heger_2010_isotope_map[282]= 253



print(heger_2010_isotope_map)
print(" ")
print(" ")
for i in np.arange(heger_2010_isotope_names.size):
    print(i,heger_2010_isotope_names[i],W18_isotope_names[heger_2010_isotope_map[i]])

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  84  85  86  87  88  89  91
  92  93  94  95  96  97  99 101 102 103 104 105 106 107 108 111 112 113
 114 115 116 119  83  90  98 100 109 110 117 118 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 136 137 138 139 140 141 142 143 144
 146 147 148 149 150 151 152 153 154 155 156 158 159 160 161 162 163 164
 165 168 169 170 171 172 173 174 175 178 179 180 181 182 183 184 187 188
 189 191 145 167 176 177 185 186 190 192 193 194 195 196 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 215 216 217 218 219 220
 221 223 224 225 226 227 228 229 230 231 232 233 234 235 236 239 240 241
 242 243 244 245 247 248 249 250 251 252 254 255 25

## Box 6 sets the isotope names from the N20 and W18 models that all other models will be mapped to

In [6]:
#Box 6
 
#Isotope Names

#N20

files = os.listdir(dir+"nucleosynthesis_yields/N20")
#print(len(files))
#print(files)
#data = np.genfromtxt(dir+"nucleosynthesis_yields/N20/"+files[0],dtype='str')
data = np.loadtxt(dir+"nucleosynthesis_yields/N20/"+files[0],skiprows=1,usecols=(0),dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
#print(np.shape(data))
#print(data)
N20_isotope_names = data    

#W18

files = os.listdir(dir+"nucleosynthesis_yields/W18")
#print(len(files))
#print(files)
#data = np.genfromtxt(dir+"nucleosynthesis_yields/W18/"+files[0],dtype='str')
data = np.loadtxt(dir+"nucleosynthesis_yields/W18/"+files[0],skiprows=1,usecols=(0),dtype='str') #, delimiter=" ", skiprows=6, usecols=1)
#print(np.shape(data))
for i in np.arange(len(data)):
    #print(i,data[i])
    W18_isotope_names = data 
    



## Box 7 defines "big data" for the SN and Wind models for W18 and N20

In [7]:
#Box 7

#Big Data
W18_big_data_SN=W18_big_data[:,:,0]
W18_big_data_wind=W18_big_data[:,:,1]
N20_big_data_SN=N20_big_data[:,:,0]
N20_big_data_wind=N20_big_data[:,:,1]

## Box 8 defines the function that changes the array of isotopes to an array of the elements

In [8]:
# Box 8

def isotopes_to_elements(isotopes):
    elements=np.zeros(119)
    elements[0]=0
    elements[1]=np.sum(isotopes[0:2])
    elements[2]=np.sum(isotopes[2:4])
    elements[3]=np.sum(isotopes[4:6])
    elements[4]=np.sum(isotopes[6:7])
    elements[5]=np.sum(isotopes[7:9])
    elements[6]=np.sum(isotopes[9:11])
    elements[7]=np.sum(isotopes[11:13])
    elements[8]=np.sum(isotopes[13:16])
    elements[9]=np.sum(isotopes[16:17])
    elements[10]=np.sum(isotopes[17:20])
    elements[11]=np.sum(isotopes[20:21])
    elements[12]=np.sum(isotopes[21:24])
    elements[13]=np.sum(isotopes[24:25])
    elements[14]=np.sum(isotopes[25:28])
    elements[15]=np.sum(isotopes[28:29])
    elements[16]=np.sum(isotopes[29:33])
    elements[17]=np.sum(isotopes[33:35])
    elements[18]=np.sum(isotopes[35:38])
    elements[19]=np.sum(isotopes[38:41])
    elements[20]=np.sum(isotopes[41:47])
    elements[21]=np.sum(isotopes[47:48])
    elements[22]=np.sum(isotopes[48:53])
    elements[23]=np.sum(isotopes[53:55])
    elements[24]=np.sum(isotopes[55:59])
    elements[25]=np.sum(isotopes[59:60])
    elements[26]=np.sum(isotopes[60:64])
    elements[27]=np.sum(isotopes[64:65])
    elements[28]=np.sum(isotopes[65:70])
    elements[29]=np.sum(isotopes[70:72])
    elements[30]=np.sum(isotopes[72:77])
    elements[31]=np.sum(isotopes[77:79])
    elements[32]=np.sum(isotopes[79:84])
    elements[33]=np.sum(isotopes[84:85])
    elements[34]=np.sum(isotopes[85:91])
    elements[35]=np.sum(isotopes[91:93])
    elements[36]=np.sum(isotopes[93:99])
    elements[37]=np.sum(isotopes[99:101])
    elements[38]=np.sum(isotopes[101:105])
    elements[39]=np.sum(isotopes[105:106])
    elements[40]=np.sum(isotopes[106:111])
    elements[41]=np.sum(isotopes[111:112])
    elements[42]=np.sum(isotopes[112:119])
    elements[44]=np.sum(isotopes[119:126])
    elements[45]=np.sum(isotopes[126:127])
    elements[46]=np.sum(isotopes[127:133])
    elements[47]=np.sum(isotopes[133:135])
    elements[48]=np.sum(isotopes[135:143])
    elements[49]=np.sum(isotopes[143:145])
    elements[50]=np.sum(isotopes[145:155])
    elements[51]=np.sum(isotopes[155:157])
    elements[52]=np.sum(isotopes[157:165])
    elements[53]=np.sum(isotopes[165:166])
    elements[54]=np.sum(isotopes[166:175])
    elements[55]=np.sum(isotopes[175:176])
    elements[56]=np.sum(isotopes[176:183])
    elements[57]=np.sum(isotopes[183:185])
    elements[58]=np.sum(isotopes[185:189])
    elements[59]=np.sum(isotopes[189:190])
    elements[60]=np.sum(isotopes[190:197])
    elements[62]=np.sum(isotopes[197:204])
    elements[63]=np.sum(isotopes[204:206])
    elements[64]=np.sum(isotopes[206:213])
    elements[65]=np.sum(isotopes[213:214])
    elements[66]=np.sum(isotopes[214:221])
    elements[67]=np.sum(isotopes[211:222])
    elements[68]=np.sum(isotopes[222:228])
    elements[69]=np.sum(isotopes[228:229])
    elements[70]=np.sum(isotopes[229:236])
    elements[71]=np.sum(isotopes[236:238])
    elements[72]=np.sum(isotopes[238:244])
    elements[73]=np.sum(isotopes[244:246])
    elements[74]=np.sum(isotopes[246:251])
    elements[75]=np.sum(isotopes[251:253])
    elements[76]=np.sum(isotopes[253:260])
    elements[77]=np.sum(isotopes[260:262])
    elements[78]=np.sum(isotopes[262:268])
    elements[79]=np.sum(isotopes[268:269])
    elements[80]=np.sum(isotopes[269:276])
    elements[81]=np.sum(isotopes[276:278])
    elements[82]=np.sum(isotopes[278:282])
    elements[83]=np.sum(isotopes[282:283])
    
    return elements

## Box 8 saves all variables from this notebook

In [9]:
# Box 8

dir=dircommand


import dill
dill.dump_session('all_model_data.db')

print('END OF NOTEBOOK 1')

END OF NOTEBOOK 1
